# Generated by Django 4.0.5 on 2022-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='moviegenre', to='movies.genre'),
        ),
    ]
