# Generated by Django 4.0.5 on 2022-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_qrcodepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodepayment',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
