# Generated by Django 4.0.5 on 2022-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_qrcodepayment_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloaded',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='qrcodepayment',
            name='amount',
            field=models.IntegerField(default='11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcodepayment',
            name='code',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
