# Generated by Django 4.0.5 on 2022-07-24 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_alter_downloaded_options_qrcodepayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodepayment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qrcodepayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
