# Generated by Django 4.0.5 on 2022-08-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_salesummary_qrcodepayment_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='Cover Images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='qrcodepayment',
            name='code',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
