# Generated by Django 4.0.3 on 2022-08-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_upcoming_alter_qrcodepayment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='image',
            field=models.ImageField(upload_to='Cover Images'),
        ),
    ]
